name: gradle-javacpp
on: [push, pull_request, workflow_dispatch]
env:
  CI_DEPLOY_MODULE: .
  CI_DEPLOY_NEED_GRADLE: 1
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
  linux-x86_64:
    runs-on: ubuntu-20.04
    container: centos:7
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-centos@actions
